// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg_jgeS2GE74OL1nIYf6qLHoPBSm_QXw0',
    appId: '1:501529260199:web:867f35fe1b02a6cc2c6b82',
    messagingSenderId: '501529260199',
    projectId: 'chess-a3c08',
    authDomain: 'chess-a3c08.firebaseapp.com',
    storageBucket: 'chess-a3c08.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPzwC0GtC6lk2fNOpvY5IjsP7-QDV_wn0',
    appId: '1:501529260199:android:bda02d8b719a33db2c6b82',
    messagingSenderId: '501529260199',
    projectId: 'chess-a3c08',
    storageBucket: 'chess-a3c08.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNYWBA2qwH_3C5mwk6Xpp7NaF04XPus8A',
    appId: '1:501529260199:ios:604b9d3f23d2ce672c6b82',
    messagingSenderId: '501529260199',
    projectId: 'chess-a3c08',
    storageBucket: 'chess-a3c08.appspot.com',
    iosClientId: '501529260199-h2gtg4mhso46fpcdpbuepq9s8bo76u3g.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNYWBA2qwH_3C5mwk6Xpp7NaF04XPus8A',
    appId: '1:501529260199:ios:604b9d3f23d2ce672c6b82',
    messagingSenderId: '501529260199',
    projectId: 'chess-a3c08',
    storageBucket: 'chess-a3c08.appspot.com',
    iosClientId: '501529260199-h2gtg4mhso46fpcdpbuepq9s8bo76u3g.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );
}
